export default {
  suratKematian,
  suratSKCK,
  suratKelahiran,
  suratAhliWaris,
  suratKehilangan,
  suratPengantarKTP,
  suratPengantarKK,
  suratIzinKeramaian,
  suratJandaDuda,
  suratPenghasilanOrangTua,
  suratKeteranganTanah,
  suratBedaNama,
  suratBepergian,
  suratBPJSKIS,
  suratAktifSekolahKuliah,
  suratNikah,
};
